# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, max_length=250)),
                ('ups', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images')),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
