# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181214_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Propic',
            field=models.ImageField(default=b'profile_pics/default.png', upload_to=b'profile_pics/'),
        ),
    ]
