# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-14 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181214_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Propic',
            field=models.ImageField(default=b'propics/default.png', upload_to=b'propics/'),
        ),
    ]
