# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181214_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Propic',
            field=models.ImageField(default=b'Banners/propics/default.png', upload_to=b'Banners/propics/'),
        ),
    ]
