# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-19 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181214_0702'),
        ('posts', '0006_auto_20181214_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(blank=True, max_length=300, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_id', models.IntegerField(blank=True, default=0, null=True)),
                ('buy', models.CharField(blank=True, max_length=200, null=True)),
                ('sell', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_loss', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('trade_time', models.CharField(blank=True, max_length=100, null=True)),
                ('ups', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('Exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Exchange')),
            ],
        ),
    ]
