# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_signels_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signels',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
