# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20181221_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='posts.Profile'),
        ),
    ]
