# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-03 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_profile_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.AddField(
            model_name='profile',
            name='followerCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='followingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follower',
            name='theUserWhoIsFollowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theUserWhoIsFollowing', to='posts.Profile'),
        ),
        migrations.AddField(
            model_name='follower',
            name='userWhoIsBeingFollowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originalUserWhoIsBeingFollowed', to='posts.Profile'),
        ),
    ]
