# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190104_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_is_being_followed', to='posts.Profile')),
                ('Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_is_following', to='posts.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='profile',
            name='Follow',
            field=models.ManyToManyField(through='posts.Relationship', to='posts.Profile'),
        ),
    ]
