# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-05 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20190105_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='Followed',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='Following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Follow',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='posts.Profile'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
