# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20190105_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='followed_by', to='posts.Profile'),
        ),
    ]
