# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-07 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0021_auto_20190105_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='Following',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
