# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20190128_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='signels',
            name='values_in',
            field=models.CharField(choices=[(b'BTC', b'BTC'), (b'USD', b'USD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Propic',
            field=models.ImageField(default=b'Banners/propics/boy.png', upload_to=b'Banners/propics/'),
        ),
    ]
