# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20190129_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweeter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
