# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0026_auto_20190130_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signels',
            name='down',
        ),
        migrations.RemoveField(
            model_name='signels',
            name='ups',
        ),
        migrations.AddField(
            model_name='signels',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='user_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signels',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
