# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20190222_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='signels',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
