# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_signels_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signels',
            name='count',
        ),
    ]
