# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_remove_signels_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Propic',
            field=models.ImageField(default=b'propics/default.png', upload_to=b'Banners/propics/'),
        ),
    ]
