# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-14 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_headline', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Banners/')),
                ('background_banner', models.ImageField(blank=True, null=True, upload_to='Banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Propic', models.ImageField(blank=True, null=True, upload_to='Banners/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
