# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-14 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coin_name', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Banners')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coin_listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(blank=True, max_length=300, null=True)),
                ('coin_id', models.IntegerField(null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_image', models.ImageField(blank=True, null=True, upload_to='Banners')),
                ('site_name', models.CharField(blank=True, max_length=300, null=True)),
                ('market_status', models.CharField(blank=True, max_length=300, null=True)),
                ('market_image', models.ImageField(blank=True, null=True, upload_to='Banners')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=300, null=True)),
                ('item_pic', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('item_price', models.IntegerField(default=0)),
                ('item_url', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(blank=True, max_length=300, null=True)),
                ('signal_id', models.IntegerField(default=0)),
                ('buy', models.CharField(blank=True, max_length=200, null=True)),
                ('sell', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_loss', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='coin_listings',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Exchange'),
        ),
    ]
