# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-22 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180914_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='item_pic',
            new_name='itempic',
        ),
    ]
