# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180922_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
