# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180928_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='signels',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
