# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_signels_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signels',
            name='signal_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
