# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181025_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_listings',
            name='cymbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coin_listings',
            name='coin_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
