# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-14 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_airdrop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='signels',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='signels',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signels',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signels',
            name='trade_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signels',
            name='ups',
            field=models.IntegerField(default=0),
        ),
    ]
