# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-19 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181214_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signels',
        ),
    ]
