# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_delete_signels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashconf',
            name='market_status',
        ),
    ]
