# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_delete_dashconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_image', models.ImageField(blank=True, null=True, upload_to='Banners')),
                ('site_name', models.CharField(blank=True, max_length=300, null=True)),
                ('market_image', models.ImageField(blank=True, null=True, upload_to='Banners')),
            ],
        ),
    ]
