# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_dashconfig_market_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Banners'),
        ),
    ]
