# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190129_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashconfig',
            name='event_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
