# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-17 16:25
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('box_image', models.ImageField(blank=True, null=True, upload_to='Blog/')),
                ('published_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
