# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
